endpoints:
  enabled: true
  sensitive: false
info:
  java:
    source: "${java.version}"
logging:
  level:
    root: INFO
management:
  health:
    mongo:
      enabled: true
  info:
    build:
      enabled: true
    git:
      mode: full
server:
  port: 8095
  context-path: /election
spring:
  application:
    name: Election Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/elections
  rabbitmq:
    host: localhost
---
spring:
  profiles: kub-aks
server:
  port: 8080
logging:
  level:
    root: INFO
management:
  info:
    build:
      enabled: true
    git:
      mode: simple
endpoints:
  env:
    keys-to-sanitize: .*password.*,.*secret.*, .*spring.data.mongodb.uri.*, .*SPRING_DATA_MONGODB_URI.*, .*spring.rabbitmq.host.*, .*SPRING_RABBITMQ_HOST.*
  configprops:
    keys-to-sanitize: .*password.*,.*secret.*, .*spring.data.mongodb.uri.*, .*SPRING_DATA_MONGODB_URI.*, .*spring.rabbitmq.host.*, .*SPRING_RABBITMQ_HOST.*
